-- Creates a table users

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(225) NOT NULL UNIQUE,
    name VARCHAR(225),
    country VARCHAR ENUM('US', 'CO', 'TN') DEFAULT 'US' NEVER NULL
)
